import { ProjectCardType } from "../../../common.types";

export const dummy_projects:ProjectCardType[] = [
    {
    id: "ccgh223",
    title: "landing page",
    reviews: 8,
    price: 99,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis eveniet deserunt repellendus aperiam saepe nemo alias optio cumque, molestiae, ",
    stars: 3,
    img: "/assets/img/dummy-product-img.png",
    },
    {
      id: "ccgh223",
      title: "landing page",
      reviews: 8,
      price: 99,
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis eveniet deserunt repellendus aperiam saepe nemo alias optio cumque, molestiae, ",
      stars: 3,
      img: "/assets/img/dummy-product-img.png",
    },
    {
      id: "ccgh223",
      title: "landing page",
      reviews: 8,
      price: 99,
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis eveniet deserunt repellendus aperiam saepe nemo alias optio cumque, molestiae, ",
      stars: 3,
      img: "/assets/img/dummy-product-img.png",
    },
    {
      id: "ccgh223",
      title: "landing page",
      reviews: 8,
      price: 99,
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis eveniet deserunt repellendus aperiam saepe nemo alias optio cumque, molestiae, ",
      stars: 3,
      img: "/assets/img/dummy-product-img.png",
    },
    {
      id: "ccgh223",
      title: "landing page",
      reviews: 8,
      price: 99,
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis eveniet deserunt repellendus aperiam saepe nemo alias optio cumque, molestiae, ",
      stars: 3,
      img: "/assets/img/dummy-product-img.png",
    },
    {
      id: "ccgh223",
      title: "landing page",
      reviews: 8,
      price: 99,
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis eveniet deserunt repellendus aperiam saepe nemo alias optio cumque, molestiae, ",
      stars: 3,
      img: "/assets/img/dummy-product-img.png",
    },
  ]